# Generated by Django 5.2 on 2025-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_film_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_post',
            name='director',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='film_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='filmimgs'),
        ),
    ]
