# Generated by Django 5.2 on 2025-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_film_post_director_film_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_post',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='film_post',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
