# Generated by Django 5.2 on 2025-04-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_film_post_slug_alter_film_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categoriesmedia'),
        ),
    ]
